name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/multi-client ./client
             docker build -t vivek091195/multi-nginx -f Dockerfile.dev ./nginx
             docker build -t vivek091195/multi-server ./server
             docker build -t vivek091195/multi-server ./worker

      # - name: Run the tests
      #   run: docker run -e CI=true vivek091195/multi-container-docker-app npm run test -- --coverage

      - name: Docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/multi-client
             docker push ${{secrets.DOCKER_USERNAME}}/multi-nginx
             docker push ${{secrets.DOCKER_USERNAME}}/multi-server
             docker push ${{secrets.DOCKER_USERNAME}}/multi-server
