name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run:
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Client image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/multi-client ./client
      
      - name: Build nginx
        run: docker build -t vivek091195/multi-nginx -f Dockerfile.dev ./nginx
             
      - name: Build server
        run: docker build -t vivek091195/multi-server ./server

      - name: Build worker
        run: docker build -t vivek091195/multi-server ./worker
             

      # - name: Run the tests
      #   run: docker run -e CI=true vivek091195/multi-container-docker-app npm run test -- --coverage

      - name: Push client
        run: docker push ${{secrets.DOCKER_USERNAME}}/multi-client

      - name: Push nginx
        run: docker push ${{secrets.DOCKER_USERNAME}}/multi-nginx

      - name: Push server
        run: docker push ${{secrets.DOCKER_USERNAME}}/multi-server
      
      - name: Push worker
        run: docker push ${{secrets.DOCKER_USERNAME}}/multi-worker
             
             
